### PR TITLE
bencrypt.py file ready

### PR DESCRIPTION
**Pull request by Morgan-Phoenix**
The New File bencrypt is ready with strong encryption methods
dependencies
- enrocrypt

### CODE REVIEW

**Review by pybash1 — CHANGES_REQUESTED** [review]
Everything looks good as per code! Please change casing of the documentk(variable names, function names, and similar things) to Came Case to remain consistent with the rest of the package. And that's all left.

**Comment by Morgan-Phoenix** [comment]
Ok

**Comment by Morgan-Phoenix** [comment]
Done With Case

**Review by pybash1 — CHANGES_REQUESTED** [review]
Looks, Perfect! Great work! Just add a newline after the import! that's all and approved!

**Review by pybash1 — APPROVED** [review]
Great! Highly Appreciated! And Approved!

**Pull request merged**
