### PR TITLE
Added function that converts a roman numeral to its integer equivalent

### PR DESCRIPTION
**Pull request by tosinolawore**
This creates a python function that converts any roman numeral to its integer equivalent. 

Function - convertRoman()

Example:
```
>>> print (convertRoman('MMXXI'))
2021
```

Closes issue #85 

Modified:
- Added black library for text formatting to requirements file
- Updated the gitignore file to ignore virtual environments
- Created the function and test case

### CODE REVIEW

**Comment by pybash1** [comment]
@tosinolawore Thanks for the contribution, just a question do you have any thing else you might be adding to the pull request? Else I will be happy to merge this PR

**Comment by tosinolawore** [comment]
@pybash1 I wouldn't be adding anything else to this particular PR. However, I would be adding other features in a different issue and PR. Please feel free to merge this PR. Thanks.

**Comment by pybash1** [comment]
Ok @tosinolawore.

**Comment by pybash1** [comment]
@tosinolawore could you please update the PR sot he checks pass just add typehints and etc.

**Comment by tosinolawore** [comment]
@pybash1 yeah sure! I've just done that.

**Comment by tosinolawore** [comment]
@pybash1 some checks require your approval. You could check the updated PR again.

**Comment by pybash1** [comment]
@tosinolawore I approved the checks, and am merging the PR now.

**Comment by tosinolawore** [comment]
@pybash1 sounds good. Thanks

**Pull request merged**
