### PR TITLE
Fix #62

### LINKED ISSUE #62: (PYL-W0123) Audit required: Use of `eval`
## Description
Use of possibly insecure function - consider using safer `ast.literal_eval`. Read more on why should `eval` be avoided [here](https://stackoverflow.com/questions/1933451/why-should-exec-and-eval-be-avoided).

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/pybash1/py_everything/issue/PYL-W0123/occurrences/](https://deepsource.io/gh/pybash1/py_everything/issue/PYL-W0123/occurrences/)

### PR DESCRIPTION
**Pull request by Morgan-Phoenix**
Fixed the security issue #62 used `ast.literal_eval`

### CODE REVIEW

**Review by pybash1 — CHANGES_REQUESTED** [review]
The code seems ok, but test fail for this function!?

**Comment by Morgan-Phoenix** [comment]
Yeah I see

**Comment by pybash1** [comment]
So how do you fix it?

**Comment by Morgan-Phoenix** [comment]
We can't use literal eval that's all
Or we have to return a num but process strings in the func

**Comment by pybash1** [comment]
@Morgan-Phoenix that can be done. We can just convert the answer to int using `int()` while returning?

**Comment by Morgan-Phoenix** [comment]
Not exactly

**Comment by pybash1** [comment]
Why so?

**Pull request merged**
