### PR TITLE
Fixed Function Issue

### PR DESCRIPTION
**Pull request by Morgan-Phoenix**
Now The Function Will Raise An Error If Wrong Type Is Provided

### CODE REVIEW

**Review by pybash1 — CHANGES_REQUESTED** [review]
All looks good. Just add a bit of space around the lines. Also would be great if you could add the type for the arguments of the function(s). e.g. - `writeData: str`

**Comment by Morgan-Phoenix** [comment]
I'll do so

**Review by pybash1 — CHANGES_REQUESTED** [review]
Looks good just add a newline after `from . Import error`. And before `def TypeError()`

**Comment by Morgan-Phoenix** [comment]
Added New Lines

**Pull request merged**
